config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dishes, only: [:show, :update]
  
  resources :chefs, only: :show do
    scope module: 'chefs' do
      resources :ingredients, only: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  validates_presence_of :name
  has_many :dishes
  has_many :dish_ingredients, through: :dishes
  has_many :ingredients, through: :dish_ingredients

  def uniq_ingredients
    self.ingredients.distinct
  end

  def top_3_ingredients
    self.ingredients.select('ingredients.*, count(ingredients) as times_used').group(:id).order(times_used: :desc).limit(3)
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates_presence_of :name, :description
  belongs_to :chef
  has_many :dish_ingredients
  has_many :ingredients, through: :dish_ingredients

  def total_calories
    self.ingredients.sum(:calories)
  end
end

app/models/dish_ingredient.rb
class DishIngredient < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :dish_ingredients
  has_many :dishes, through: :dish_ingredients
  has_many :chefs, through: :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chefs/ingredients_controller.rb
module Chefs
  class IngredientsController < ApplicationController
    
    def index
      @chef = Chef.find(params[:chef_id])
      @ingredients = @chef.uniq_ingredients
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  def show
    @chef = Chef.find(params[:id])
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  
  def show
    @dish = Dish.find(params[:id])
  end

  def update
    if Dish.where(id: params[:dish_id]).empty?
      redirect_to chef_path(params[:chef_id])
      flash[:error] = "That is not a valid dish id"

    else
      dish = Dish.find(params[:dish_id])
      dish.update(dish_params)
      redirect_to chef_path(params[:chef_id])
    end
  end

  private

  def dish_params
    params.permit(:name, :description, :chef_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chefs/ingredients/index.html.erb
<h1><%= "#{@chef.name}'s Ingredients" %></h1>
<ul>
  <% @ingredients.each do |ingredient|  %>
    <li><%= ingredient.name %></li>
  <% end %>
</ul>

app/views/chefs/show.html.erb
<h1><%= @chef.name %></h1>
<h3>Dishes: </h3>
<ul>
  <% @chef.dishes.each do |dish| %>
    <li>
      <%= dish.name %>
    </li>
  <% end %>
</ul>
<%= form_with url: "/dishes/edit", local: true, method: :patch do |form| %>
  <p>
  <%= form.label :dish_id, "Add a dish via it's ID:" %>
  <%= form.number_field :dish_id %>
  <%= form.hidden_field :chef_id, value: @chef.id %>
  <%= form.submit 'Submit' %>
  </p>
<% end %>
<br>
<%= button_to "View #{@chef.name}'s Ingredients", chef_ingredients_path(@chef), method: :get %>

<h4>3 most popular ingredients in these recipes:</h4>
<ol id="top3">
  <% @chef.top_3_ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ol>

app/views/dishes/show.html.erb
<h1><%= @dish.name %></h1>
<p><%= "Created by Chef #{@dish.chef.name}" %>
<h3>Description: <%= @dish.description %></h3>
<h4>Ingredients: </h4>
<ul>
  <% @dish.ingredients.each do |ingredient| %>
    <li>
      <%= "#{ingredient.name} (#{ingredient.calories} calories)" %>
    </li>
  <% end %>
</ul>
<h4>Calories: <%= @dish.total_calories %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>